In [1]:
import numpy as np

In [3]:
# dir(np)

In [6]:
lst1 = [1,2,3,4]
lst2 = [1,2,3,4]

In [7]:
lst1 + lst2

[1, 2, 3, 4, 1, 2, 3, 4]

In [11]:
arr1 = np.array(lst1)
arr2 = np.array(lst2)

In [12]:
arr1

array([1, 2, 3, 4])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr2

array([1, 2, 3, 4])

In [15]:
arr1 + arr2 

array([2, 4, 6, 8])

In [16]:
arr1 * arr2

array([ 1,  4,  9, 16])

In [25]:
lst1 = [ [ 1,2,3 ] , [ 3,4,5 ] , [ 4,5,6 ]  ]
mat1 = np.array(lst)
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [26]:
lst2 = [ [ 3,2,3 ] , [ 5,4,5 ] , [ 6,5,6 ]  ]
mat2 = np.array(lst2)
mat2

array([[3, 2, 3],
       [5, 4, 5],
       [6, 5, 6]])

In [27]:
lst1 + lst2 

[[1, 2, 3], [3, 4, 5], [4, 5, 6], [3, 2, 3], [5, 4, 5], [6, 5, 6]]

In [28]:
mat1 + mat2 

array([[ 4,  4,  6],
       [ 8,  8, 10],
       [10, 10, 12]])

In [29]:
mat1 * mat2 

array([[ 3,  4,  9],
       [15, 16, 25],
       [24, 25, 36]])

In [30]:
mat1.dot(mat2)

array([[31, 25, 31],
       [59, 47, 59],
       [73, 58, 73]])

In [31]:
# [1, 2, 3] 
# [3, 5, 6] 

3 + 10 + 18 

31

In [32]:
# [1, 2, 3]
# [2, 4, 5]
2 + 8 + 15

25

In [43]:
v1 = np.array([1,2,3])
v1

array([1, 2, 3])

In [44]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [45]:
v1 + mat1

array([[2, 4, 6],
       [4, 6, 8],
       [5, 7, 9]])

In [53]:
v2 = np.array([[1],[2],[3]])
v2

array([[1],
       [2],
       [3]])

In [54]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [55]:
v2 + mat1

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [56]:
s = 5 

In [57]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [58]:
s * mat1

array([[ 5, 10, 15],
       [15, 20, 25],
       [20, 25, 30]])

In [59]:
v1 

array([1, 2, 3])

In [60]:
v1 * s

array([ 5, 10, 15])

In [61]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [65]:
lst1

[[1, 2, 3], [3, 4, 5], [4, 5, 6]]

In [66]:
lst1[0]

[1, 2, 3]

In [64]:
mat1[0]

array([1, 2, 3])

In [67]:
lst1[-1]

[4, 5, 6]

In [68]:
mat1[-1]

array([4, 5, 6])

In [69]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [73]:
# mat1[rows , cols]
mat1[ 0: , 0:1]

array([[1],
       [3],
       [4]])

In [77]:
mat1[: , -1:]

array([[3],
       [5],
       [6]])

In [78]:
mat1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [81]:
mat1[:2 , :2]

array([[1, 2],
       [3, 4]])

In [82]:
mat1[1: , 1:]

array([[4, 5],
       [5, 6]])

In [86]:
np.zeros([3,3] ,dtype = int)    #dtype = float

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [87]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
m = np.zeros((10,10))
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
m.shape

(10, 10)

In [92]:
m.shape[0]

10

In [93]:
m.shape[1]

10

In [94]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
m[1:-1 , 1 : -1 ] = 1

In [97]:
m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
m1 = np.zeros((10,10))
m1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [104]:
m1[0]   = 1
m1[-1]  = 1
m1[:,0] = 1 
m1[:,-1]= 1
m1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [125]:
# import random as rn
# rn.random()
np.random.random((3,3))  # 0 : 1 

array([[0.11997516, 0.58460176, 0.69630332],
       [0.63793629, 0.87435391, 0.97690238],
       [0.91225423, 0.44435506, 0.52235894]])

In [160]:
np.random.seed(12)
data = np.random.randint(1 , 10 , (20,5))
data

array([[7, 2, 3, 4, 4],
       [1, 7, 2, 5, 6],
       [3, 7, 1, 6, 9],
       [3, 4, 5, 4, 2],
       [8, 1, 3, 7, 3],
       [1, 5, 7, 1, 1],
       [9, 7, 2, 9, 5],
       [1, 5, 2, 6, 6],
       [4, 5, 6, 6, 1],
       [7, 7, 4, 3, 5],
       [4, 7, 8, 5, 2],
       [5, 6, 4, 6, 1],
       [3, 7, 5, 8, 7],
       [3, 4, 3, 7, 5],
       [6, 1, 1, 6, 5],
       [1, 4, 8, 7, 9],
       [7, 2, 5, 7, 6],
       [3, 5, 1, 9, 5],
       [5, 4, 8, 4, 7],
       [2, 5, 4, 9, 9]])

In [142]:
def train_test_split(d , p ):
    
    
    return x_train , x_test , y_train , y_test

# x_train , x_test , y_train , y_test = train_test_split(data , per = .5)

In [154]:
per = .8   # > train 60% and test 40%
int(data.shape[0] * per)

14

In [156]:
train = data[0: int(data.shape[0] * per) , :]

In [157]:
test = data[int(data.shape[0] * per) : , :]

In [158]:
test.shape

(6, 5)

In [159]:
train.shape

(14, 5)

In [161]:
train

array([[7, 2, 3, 4, 4],
       [1, 7, 2, 5, 6],
       [3, 7, 1, 6, 9],
       [3, 4, 5, 4, 2],
       [8, 1, 3, 7, 3],
       [1, 5, 7, 1, 1],
       [9, 7, 2, 9, 5],
       [1, 5, 2, 6, 6],
       [4, 5, 6, 6, 1],
       [7, 7, 4, 3, 5],
       [4, 7, 8, 5, 2],
       [5, 6, 4, 6, 1],
       [3, 7, 5, 8, 7],
       [3, 4, 3, 7, 5]])

In [162]:
y_train = train[: , -1]

In [163]:
y_train

array([4, 6, 9, 2, 3, 1, 5, 6, 1, 5, 2, 1, 7, 5])

In [164]:
x_train = train[: , 0:-1]
x_train

array([[7, 2, 3, 4],
       [1, 7, 2, 5],
       [3, 7, 1, 6],
       [3, 4, 5, 4],
       [8, 1, 3, 7],
       [1, 5, 7, 1],
       [9, 7, 2, 9],
       [1, 5, 2, 6],
       [4, 5, 6, 6],
       [7, 7, 4, 3],
       [4, 7, 8, 5],
       [5, 6, 4, 6],
       [3, 7, 5, 8],
       [3, 4, 3, 7]])

In [166]:
# for i in range(10):
#     print(i)

In [169]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
a.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [172]:
a.reshape((10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [173]:
a.reshape([5,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [176]:
np.linspace(1,10,6).reshape([2,3])

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [177]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
np.concatenate((a,a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [181]:
np.hstack((a,a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [184]:
vstack = np.vstack((a,a))
vstack

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [186]:
np.vstack(( vstack, a ))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [192]:
np.empty([3,4])

array([[1.40880217e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.37959197e-306, 2.90456949e+180, 1.81657307e-052,
        3.85777890e-057],
       [7.93318349e+165, 1.11622566e+165, 1.72254395e+184,
        2.00325639e-076]])