In [1]:
import numpy as np 

In [7]:
arr = np.array([1,2,3,4,5,6])

In [8]:
np.mean(arr)

3.5

In [9]:
(1+2+3+4+5+6) / 6

3.5

In [10]:
arr.mean()

3.5

In [11]:
np.median(arr)

3.5

In [15]:
round(np.var(arr) , 2)

2.92

In [17]:
round(np.std(arr) , 2)

1.71

In [19]:
round(np.sqrt(2.92) , 2)

1.71

In [20]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,7,6,5,4,3,2,1])
np.cov(x,y)

array([[ 7.5, -7.5],
       [-7.5,  7.5]])

In [22]:
np.cov(x,y)[0 , 1]

-7.5

In [23]:
np.cov(x,y)[1 , 0]

-7.5

In [24]:
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [25]:
np.corrcoef(x,y)[0,1]

-1.0

In [28]:
m = np.array([[1 , 2 , 3] , [1 , 4 , 6] , [4 , 5 , 6]])
m

array([[1, 2, 3],
       [1, 4, 6],
       [4, 5, 6]])

In [31]:
round(np.mean(m) , 2)

3.56

In [32]:
round((1+2+3+1+4+6+4+5+6) / 9 , 2)

3.56

In [37]:
np.mean( m , axis= 1)   # axis = 1 >> rows

array([2.        , 3.66666667, 5.        ])

In [38]:
np.mean( m , axis= 0)   # axis = 0 >>  cols

array([2.        , 3.66666667, 5.        ])

In [39]:
m = np.array([[1 , 2 , 3] , [1 , 4 , 6] , [4 , 5 , 6]])
m

array([[1, 2, 3],
       [1, 4, 6],
       [4, 5, 6]])

In [40]:
np.median(m , axis=1)  #axis = 1 >> rows 

array([2., 4., 5.])

In [41]:
np.median(m , axis=0)  #axis = 0 >> cols 

array([1., 4., 6.])

In [44]:
np.var(m , axis = 1)

array([0.66666667, 4.22222222, 0.66666667])

In [45]:
np.std(m , axis= 1)

array([0.81649658, 2.05480467, 0.81649658])

In [46]:
# stats(data):
#     mean   0 , 1
#     median 0 , 1 
#     var    0 , 1 
#     cov    co11 , col2 
#     corr   col1 , col2
2 + 6 + 14 + 18 +10

50