In [1]:
import numpy as np

In [2]:
np.random.seed(123)
data = np.random.randint(1,10 , (20,5))

In [6]:
data

array([[3, 3, 7, 2, 4],
       [7, 2, 1, 2, 1],
       [1, 4, 5, 1, 1],
       [5, 2, 8, 4, 3],
       [5, 8, 3, 5, 9],
       [1, 8, 4, 5, 7],
       [2, 6, 7, 3, 2],
       [9, 4, 6, 1, 3],
       [7, 3, 5, 5, 7],
       [4, 1, 7, 5, 8],
       [7, 8, 2, 6, 8],
       [3, 5, 9, 2, 3],
       [2, 2, 4, 6, 1],
       [9, 2, 7, 4, 4],
       [6, 8, 3, 4, 4],
       [4, 9, 7, 8, 7],
       [4, 7, 7, 7, 2],
       [4, 5, 4, 2, 1],
       [6, 9, 7, 9, 2],
       [1, 4, 2, 4, 5]])

In [13]:
def train_test_split(data , per = .5):
    n_rows = int(data.shape[0] * per)
    train  = data[ : n_rows , :]
    test   = data[n_rows:   , :]
    x_train= train[: , :-1]
    y_train= train[: , -1:]
    x_test = test[:  , :-1]
    y_test = test[:  , -1:]
    return x_train , y_train , x_test , y_test

In [29]:
x_train , y_train , x_test , y_test = train_test_split(data , .8)

In [30]:
x_train.shape

(16, 4)

In [31]:
y_train.shape

(16, 1)

In [32]:
x_test.shape , y_test.shape

((4, 4), (4, 1))

In [37]:
x = data[: , :-1]
y = data[: , -1:]
from sklearn.model_selection import train_test_split
train_test_split(x , y , train_size=.6)

[array([[4, 7, 7, 7],
        [4, 1, 7, 5],
        [7, 8, 2, 6],
        [9, 4, 6, 1],
        [4, 5, 4, 2],
        [4, 9, 7, 8],
        [7, 2, 1, 2],
        [2, 6, 7, 3],
        [6, 8, 3, 4],
        [7, 3, 5, 5],
        [1, 4, 2, 4],
        [9, 2, 7, 4]]),
 array([[1, 4, 5, 1],
        [3, 3, 7, 2],
        [6, 9, 7, 9],
        [2, 2, 4, 6],
        [5, 2, 8, 4],
        [5, 8, 3, 5],
        [1, 8, 4, 5],
        [3, 5, 9, 2]]),
 array([[2],
        [8],
        [8],
        [3],
        [1],
        [7],
        [1],
        [2],
        [4],
        [7],
        [5],
        [4]]),
 array([[1],
        [4],
        [2],
        [1],
        [3],
        [9],
        [7],
        [3]])]

In [38]:
m = np.array([[1,2,3] , [2,3,4] , [4,5,6]])
m

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [39]:
m.shape

(3, 3)

In [40]:
m = np.array([[1,2,3] , [2,3,4] , [3,4,5]])
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
i = np.identity(4 ,dtype = int )

In [45]:
i

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
i.astype(float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
i.dtype

dtype('int32')

In [48]:
type(i)

numpy.ndarray

In [53]:
np.full((10,5) , [1,2,3,4,5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [55]:
np.full((3,3) , 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [56]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [57]:
np.tril(m)

array([[1, 0, 0],
       [2, 3, 0],
       [3, 4, 5]])

In [58]:
np.triu(m)

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 5]])

In [59]:
lst = [1,2,3,4]
np.diag(lst)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [60]:
# m.dot(m2)
# np.dot((m1,m2))

In [61]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [63]:
d = np.diag(m)

In [64]:
np.diag(d)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [66]:
np.diag(m).sum()

9

In [67]:
1 + 3 + 5 

9

In [70]:
m[0,0] + m[1,1] + m[2,2]

9

In [71]:
np.trace(m)  #m[0,0] + m[1,1] + m[2,2]

9

In [73]:
m2 = np.array([[1,2,3] , [3,4,5]])
m2

array([[1, 2, 3],
       [3, 4, 5]])

In [74]:
m2.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [76]:
m3 = np.array([[1,2] , [3,4]])
m3

array([[1, 2],
       [3, 4]])

In [77]:
(1 * 4 ) - (2 * 3 )

-2

In [78]:
np.linalg.det(m3)

-2.0000000000000004

In [79]:
m4 = np.array([[1,-2,3],[2,0,3] , [1,5,4]])
m4

array([[ 1, -2,  3],
       [ 2,  0,  3],
       [ 1,  5,  4]])

In [80]:
np.linalg.det(m4)

24.999999999999996

In [85]:
m3

array([[1, 2],
       [3, 4]])

In [86]:
np.linalg.inv(m3)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [87]:
# m.inv() = (1/det(m))
m3_ = np.array([[4, -2],[-3, 1]])
m3_

array([[ 4, -2],
       [-3,  1]])

In [88]:
(1/-2) * m3_

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
inv = np.linalg.inv(m3)

In [91]:
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
m3.dot(inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [99]:
d = np.array([[1,2,3] , [3,5,10],[1,4,5]])
d

array([[ 1,  2,  3],
       [ 3,  5, 10],
       [ 1,  4,  5]])

In [102]:
3 - 0  

3

In [101]:
np.linalg.matrix_rank(d)

3

In [105]:
m = np.array([[1,2,3],[4,2,6],[3,4,7]])
m
# m.shape[0] == m.shape[1]

array([[1, 2, 3],
       [4, 2, 6],
       [3, 4, 7]])

In [106]:
# inv
# det
# T
# trace
# rank
# tril
# triu

In [108]:
s = np.array([[1,0,0,0,0,2],[1,0,1,0,2,0],[0,0,1,2,0,1]])
s

array([[1, 0, 0, 0, 0, 2],
       [1, 0, 1, 0, 2, 0],
       [0, 0, 1, 2, 0, 1]])

In [109]:
s.size

18

In [110]:
s.shape[0] * s.shape[1]

18

In [111]:
np.count_nonzero(s)

8

In [115]:
round(1 - (np.count_nonzero(s) / s.size) , 2)

0.56

In [116]:
from scipy.sparse import csr_matrix , csc_matrix

In [117]:
s

array([[1, 0, 0, 0, 0, 2],
       [1, 0, 1, 0, 2, 0],
       [0, 0, 1, 2, 0, 1]])

In [119]:
print(csr_matrix(s))

  (0, 0)	1
  (0, 5)	2
  (1, 0)	1
  (1, 2)	1
  (1, 4)	2
  (2, 2)	1
  (2, 3)	2
  (2, 5)	1


In [120]:
print(csc_matrix(s))

  (0, 0)	1
  (1, 0)	1
  (1, 2)	1
  (2, 2)	1
  (2, 3)	2
  (1, 4)	2
  (0, 5)	2
  (2, 5)	1


In [121]:
s

array([[1, 0, 0, 0, 0, 2],
       [1, 0, 1, 0, 2, 0],
       [0, 0, 1, 2, 0, 1]])

In [122]:
spars =  csc_matrix(s)

In [123]:
spars.todense()

matrix([[1, 0, 0, 0, 0, 2],
        [1, 0, 1, 0, 2, 0],
        [0, 0, 1, 2, 0, 1]], dtype=int32)